version: "3.9"

services:

  # -------------------- Azure SQL Edge --------------------
  sqledge:
    container_name: sqledge
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongP@ssword123!"
    ports:
      - "1433:1433"  # Optional: expose for local dev
    # volumes:
    #   - sqledge-data:/var/opt/mssql
    networks:
      - sb-emulator
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "nc -z localhost 1433"]
      interval: 10s
      retries: 3

  # -------------------- Azure Service Bus Emulator --------------------
  servicebus-emulator:
    container_name: servicebus-emulator
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
       - ./servicebus-emulator:/ServiceBus_Emulator/ConfigFiles
    ports:
      - "5672:5672"       
      - "5671:5671"
      - "5300:5300"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "YourStrongP@ssword123!"
      ACCEPT_EULA: "Y"
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - sbemulatorns
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "nc -z localhost 5672"]
      interval: 5s
      timeout: 5s
      retries: 15
# ------------------------------ RabbitMQ ------------------------------
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-test
    ports:
      - "5673:5672"   # AMQP
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 12
  rabbit-init:
    image: curlimages/curl:8.9.1
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: >
      sh -c '
        until curl -su guest:guest http://rabbit:15672/api/overview >/dev/null 2>&1; do sleep 1; done;
        curl -su guest:guest -H "content-type: application/json" -X PUT
        http://rabbit:15672/api/queues/%2f/demo-messages
        -d "{\"durable\":false,\"auto_delete\":false,\"arguments\":{}}"
      '

# ------------------------ Shared Networks ---------------------------
networks:
  sb-emulator:
    driver: bridge
